title: Kyle Kavanagh ePortfolio
description: Links to github repositories.
theme: minima

minima:
  header_pages:
    - original-artifact.md
    - software-engineering.md
    - algorithms.md
    - databases.md
